<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0
 */

namespace winwin\winner\integration\kms;

use kuiper\tars\annotation\TarsClient;
use kuiper\tars\annotation\TarsParameter;
use kuiper\tars\annotation\TarsReturnType;

/**
 * @TarsClient("winwin.kms.KmsObj")
 */
interface KmsServant
{
    /**
     * @TarsParameter(name="secretNames", type="vector<string>")
     * @TarsReturnType("map<string,string>")
     *
     * @param string[] $secretNames
     *
     * @return string[]
     */
    public function getSecretValues(array $secretNames): array;
}
